[package]
name = "echor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {workspace = true}

[dev-dependencies]
rand = "0.8.5"
assert_cmd = {workspace = true}
predicates = {workspace = true}