[package]
name = "catr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap ={workspace=true}

[dev-dependencies]
rand = "0.8.5"
assert_cmd = {workspace = true}
predicates = {workspace = true}